# Generated by Django 6.0.3 on 2026-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermessage_user_profile_alter_usermessage_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='writer',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
