# Generated by Django 6.0.3 on 2026-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_signup_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='writer',
            field=models.CharField(default='Senior blog writer', max_length=100),
        ),
    ]
