# Generated by Django 6.0.3 on 2026-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_tegs_tag_remove_blogpost_tegs_blogpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='main.tag'),
        ),
    ]
