# Generated by Django 6.0.3 on 2026-04-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.blogpost'),
        ),
    ]
