# Generated by Django 6.0.3 on 2026-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_signup_profile_img_alter_usermessage_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('check_box', models.BooleanField(default=False)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
    ]
