# Generated by Django 6.0.3 on 2026-04-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_userconnects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.thread'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.signup'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='first_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_first', to='main.signup'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='second_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_second', to='main.signup'),
        ),
    ]
