# Generated by Django 6.0.3 on 2026-04-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_chatmessage_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted',
        ),
    ]
