# Generated by Django 6.0.3 on 2026-03-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Trash Bin',
                'verbose_name_plural': 'Trash Bin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('check_box', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('destinations_img', models.ImageField(blank=True, null=True, upload_to='destinations_images/')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('hotel_img', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('check_box', models.BooleanField(default=False)),
                ('import_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationsAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=50, verbose_name='Available Text')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.amenity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destinations')),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='amenities',
            field=models.ManyToManyField(related_name='destinations', through='main.DestinationsAmenity', to='main.amenity'),
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False, verbose_name='Available (Yes/No)')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(related_name='hotels', through='main.HotelAmenity', to='main.amenity'),
        ),
    ]
