# Generated by Django 6.0.3 on 2026-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='import_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
