# Generated by Django 6.0.3 on 2026-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_adminmessage_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='user_ip',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='import_time',
        ),
        migrations.AddField(
            model_name='usercontact',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
