# Generated by Django 6.0.3 on 2026-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermessage_import_time_usermessage_user_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='stars',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
