# Generated by Django 6.0.3 on 2026-03-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_ip_usercontact_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='created_at',
        ),
    ]
