# Generated by Django 6.0.3 on 2026-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_contactinfo_usermessage_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Swimming Pool' or 'Gymnesium'", max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_img', models.ImageField(blank=True, null=True, upload_to='destination-card-img/')),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='main.amenity')),
            ],
        ),
    ]
