# Generated by Django 6.0.3 on 2026-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_amenity_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_img', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('has_swimming_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Gymnesium')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-fi')),
                ('has_room_service', models.BooleanField(default=False, verbose_name='Room Service')),
                ('has_air_condition', models.BooleanField(default=False, verbose_name='Air Condition')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='Restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
