# Generated by Django 6.0.3 on 2026-03-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hotel_delete_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='has_air_condition',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_gym',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_restaurant',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_room_service',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_swimming_pool',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_wifi',
        ),
        migrations.AddField(
            model_name='hotel',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False, verbose_name='Available (Yes/No)')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(related_name='hotels', through='main.HotelAmenity', to='main.amenity'),
        ),
    ]
