# Generated by Django 6.0.3 on 2026-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tegs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tegs',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tegs',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main.tag'),
        ),
    ]
