# Generated by Django 6.0.3 on 2026-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_hotel_has_air_condition_remove_hotel_has_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
    ]
