# Generated by Django 6.0.3 on 2026-03-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_hotel_airport_hotel_date_hotel_duration_hotel_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='extras',
            field=models.CharField(blank=True, null=True),
        ),
    ]
