# Generated by Django 6.0.3 on 2026-03-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_hotel_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='extras',
        ),
    ]
