# Generated by Django 6.0.3 on 2026-03-19 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_hotel_airport_remove_hotel_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationsAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False, verbose_name='Available (Yes/No)')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.amenity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destinations')),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='amenities',
            field=models.ManyToManyField(related_name='destinations', through='main.DestinationsAmenity', to='main.amenity'),
        ),
    ]
