# Generated by Django 6.0.3 on 2026-04-03 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_usermessage_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_img',
            field=models.ImageField(blank=True, default='user-images/default.jpg', null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.blogpost'),
        ),
    ]
