# Generated by Django 6.0.3 on 2026-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_destinationsamenity_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationsamenity',
            name='is_available',
            field=models.CharField(default='', max_length=50, verbose_name='Available Text'),
        ),
    ]
