# Generated by Django 6.0.3 on 2026-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_destinationsamenity_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='destinations_img',
            field=models.ImageField(blank=True, null=True, upload_to='destinations_images/'),
        ),
    ]
