# Generated by Django 6.0.3 on 2026-04-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_thread_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConnects',
        ),
    ]
