# Generated by Django 6.0.3 on 2026-03-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_destinations_destinations_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
