# Generated by Django 6.0.3 on 2026-03-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_destinations_price_per_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationsamenity',
            old_name='is_available',
            new_name='text',
        ),
    ]
